# Generated by Django 5.2.17 on 2026-09-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
